// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.7.2

package dbmodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	passResultFieldNames          = builder.RawFieldNames(&PassResult{})
	passResultRows                = strings.Join(passResultFieldNames, ",")
	passResultRowsExpectAutoSet   = strings.Join(stringx.Remove(passResultFieldNames, "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	passResultRowsWithPlaceHolder = strings.Join(stringx.Remove(passResultFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	passResultModel interface {
		Insert(ctx context.Context, data *PassResult) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*PassResult, error)
		Update(ctx context.Context, data *PassResult) error
		Delete(ctx context.Context, id int64) error
	}

	defaultPassResultModel struct {
		conn  sqlx.SqlConn
		table string
	}

	PassResult struct {
		Id            int64          `db:"id"`              // 主键ID
		LivePhoto     string         `db:"live_photo"`      // 现场照片
		PassResult    int64          `db:"pass_result"`     // 通行记录结果 1-成功, 0-失败
		PassResultMsg string         `db:"pass_result_msg"` // 通行结果描述
		CreateTime    time.Time      `db:"create_time"`     // 创建时间
		TraceId       string         `db:"trace_id"`        // 核验流水号
		Mhid          string         `db:"mhid"`            // 通行旅客的mhid
		RequestId     sql.NullString `db:"request_id"`
		UploadStatus  int64          `db:"upload_status"` // 上传状态
	}
)

func newPassResultModel(conn sqlx.SqlConn) *defaultPassResultModel {
	return &defaultPassResultModel{
		conn:  conn,
		table: "`pass_result`",
	}
}

func (m *defaultPassResultModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPassResultModel) FindOne(ctx context.Context, id int64) (*PassResult, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", passResultRows, m.table)
	var resp PassResult
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultPassResultModel) Insert(ctx context.Context, data *PassResult) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?)", m.table, passResultRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.LivePhoto, data.PassResult, data.PassResultMsg, data.TraceId, data.Mhid, data.RequestId, data.UploadStatus)
	return ret, err
}

func (m *defaultPassResultModel) Update(ctx context.Context, data *PassResult) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, passResultRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.LivePhoto, data.PassResult, data.PassResultMsg, data.TraceId, data.Mhid, data.RequestId, data.UploadStatus, data.Id)
	return err
}

func (m *defaultPassResultModel) tableName() string {
	return m.table
}
