// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2
// Source: user.proto

package server

import (
	"context"

	"go-zero-learn/rpc/server/internal/logic/product"
	"go-zero-learn/rpc/server/internal/svc"
	"go-zero-learn/rpc/server/pb/user"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServer) Create(ctx context.Context, in *user.ProductReq) (*user.ProductResp, error) {
	l := productlogic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}
